//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer4.MicroService.Data.Views {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer4.MicroService.Data.Views.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE VIEW View_User
        ///AS
        ///SELECT
        /// D.TenantId,
        /// A.Id as UserId,
        ///(SELECT Q2.Id, Q2.Name, Q2.NormalizedName FROM AspNetUserRoles Q1
        ///JOIN AspNetRoles Q2 ON Q1.RoleId = Q2.Id
        ///WHERE UserId = A.Id FOR JSON AUTO) as Roles,
        ///
        ///(SELECT Q1.ClaimType,Q1.ClaimValue FROM AspNetUserClaims Q1
        ///WHERE Q1.UserId = A.Id FOR JSON AUTO) as Claims,
        ///
        ///(SELECT Q1.Files,Q1.FileType AS Name FROM AspNetUserFiles Q1
        ///WHERE Q1.UserId = A.Id FOR JSON AUTO) as Files,
        ///
        /// A.Avatar,
        /// A.UserName,
        /// A.Email,
        /// A.Lineage.ToString() AS  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string View_User {
            get {
                return ResourceManager.GetString("View_User", resourceCulture);
            }
        }
    }
}
