site_name: OAuthApp
repo_url: https://github.com/seven1986/OAuthApp
repo_name: seven1986/OAuthApp
copyright: 版权所有 © 2020 OAuthApp
nav:
  - 首页: 
      - 'index.md'
      - Auth2.0 授权模式:
        - 'auth-implicit.md'
        - 'auth-code.md'
        - 'auth-password.md'
        - 'auth-credentials.md'
        - 'auth-hybrid.md'
  - 开始使用:
      - 'start-server.md'
      - 'settings.md'
      - 'azureblob.md'
      - 'sendcloud.md'
  - 实例:
        - 'extend-validator.md'
        - 'saas.md'
        - 'authlogins.md'
        - 'userinteraction.md'
  - 参考: 
        - 'scopes.md'
        - 'apidocument.md'
        - 'oauthappswagger.md'
        - 'doc-extensions.md'
  - 更新日志: 
      - 'logs.md'
theme:
  name: material
  custom_dir: overrides
  favicon: images/oauthapp.png
  features:
    - navigation.tabs
    - navigation.sections
  logo: images/oauthapp.png
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seven1986/OAuthApp
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
plugins:
  - git-revision-date
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - search
  - redirects:
      redirect_maps:
        'apidocument.md': 'https://www.oauthapp.com/docs/index.html'
        'oauthappswagger.md': 'https://www.oauthapp.com/swagger'